title: Clara Regalado
logo: /assets/img/foto.jpg
description: A Data Scientis working as a Test Engineer. Currently studying a master degree in AI and Machine Learning. I had a bachelor's degree in Mathematics and I was looking for a new possibility for my career. I started to review different paths and I found Data Science an intriguing choice which matched my background, my skills, necessities and expectations. I have experience with Business, Optimization, and Actuarial fields. Now I am seeking for new challenges to explote my potential, abilities and skills and provided me an opportunity to shine.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
